### ISSUE TITLE
Suggestion new features - Min/Max characters of tags

### ISSUE THREAD

**Issue by edukmattos** [panuavakul/material_tag_editor#21]
Congratulations for the package !
I have a suggestion:
Limit size(lenght) min and max of tags

**Comment by panuavakul** [comment]
Hi @edukmattos , thanks for the suggestion.
Maybe it is possible to include some kind of validation callback so that can be used to check if the new tag is valid or not.
I have to think more about this so please give me sometime.

**Comment by clay4649** [comment]
@edukmattos Hi and sorry for my extremely late reply. You could now do this in 0.1.2 using the inputFormatter prop.

Maybe something like this.

```
inputFormatters: [LengthLimitingTextInputFormatter(15)],
```

**Comment by clay4649** [comment]
If you need anymore help with with please create another issue. I will close this for now.
Thanks

**Comment by Najki** [comment]
For min length, I've came up with such workaround. It's not perfect, because the invalid text disappears, but in some cases it may be better than nothing. You could also set `resetTextOnSubmitted: false` so the invalid text won't disappear when enter/done is pressed, but I haven't found such workaround for delimiter - that one always causes the invalid text to disappear.

```dart
final FocusNode focus = FocusNode();
// ...

            focusNode: focusNode,
            onTagChanged: (String inputValue) {
              if (!isValid(inputValue)) {
                return;
              }
              // add tag to list
            },
            onSubmitted: (String inputValue) {
              if (!isValid(inputValue)) {
                focusNode.requestFocus();
                return;
              }
              // add tag to list
            },

// ...

  bool isValid(String item) {
    return item.isNotEmpty && item.trim().length >= 2;
  }
```

However, it would be nice to get some kind of validator support, because `inputFormatters` make sens only for max length, but not for min length.
