### ISSUE TITLE
Why use CustomMultiChildLayout

### ISSUE THREAD

**Issue by Nolence** [panuavakul/material_tag_editor#33]
Question, why do you define a CustomMultiChildLayout? Is there a technical reason for it?

I was reading through the code and thought it would be implemented with something like a `Wrap` but the actual implementation looks a lot more complicated. Do you need a CustomLayout in order to correctly place the TextField beside the tags?

Just curious

**Comment by panuavakul** [comment]
Hi @Nolence , thanks for your question. Unfortunately, I do not have much memory left of when I was initially writing this 🤣
I imagine it have something to do with laying out the TextField on the left over space on the right of the tags. Since I do not think that `Wrap` give you the left over space (correct me if I am wrong).

If you happen to know a simpler way of doing this please let me know 😋

**Comment by Nolence** [comment]
Sorry, didn't mean to imply anything was wrong or could be improved, just thought I'd ask as it was interesting at the time. Yeah that explanation sounds correct to me.

Thanks for you package too !
