### ISSUE TITLE
Expose on TextField valueChanged and onSubmitted

### ISSUE THREAD

**Issue by basilmariano** [panuavakul/material_tag_editor#8]
This will make it more flexible to use

**Comment by panuavakul** [comment]
@basilmariano 
Thanks for the feedback and sorry for the late reply, I will be exposing onSubmitted on the next release.
However, could you give me some use case or valueChanged?  Since we are using the `TextField` 's onChanged for adding tag, adding a custome onChanged is quite a mess, since you have to deal with the timing of calling onChanged before or after the process of calling onTagChanged.

**Comment by panuavakul** [comment]
Going to close this for now. Please feel free to open a new issue about this. Thanks

**Comment by giacomok** [comment]
I guess we could use onChanged for autocomplete function.
